### ISSUE TITLE
Debug assert in sortedness test (Windows)

### ISSUE THREAD

**Issue by tanaya-mankad** [bigladder/btwxt#34]
The test `GridAxis.vector_is_sorted` asserts std::is_sorted's "invalid comparator" message on Windows, indicating that the [comparator function](https://github.com/bigladder/btwxt/blob/b4d0e17c3fff937715007201e2e9dc4ee8c06ad0/include/btwxt/grid-axis.h#L86) offered to std::is_sorted() doesn't obey strict weak ordering. Without strict weak ordering, associative containers (set, map, etc) could exhibit undefined behavior, so it's helpful that msvc offers an unobtrusive way to find this potential error (i.e. a debug-build assert). 

However, this means that our comparator function `[](const double a, const double b) { return a <= b; })` is always going to assert on Windows-debug, because it isn't strict. The "strict" of 'strict weak' means that if you compare _a_ with _a_ (two instances that are equal), the operator should return false. Therefore `<=` isn't allowed, only `<`. The "weak" part just means that within a sorted set, you're allowed to have ties between _equivalent_ instances, even if those instances are not _equal_. (For PODs, of course, equivalence is the same as equality, but it needn't be for all object types.)

The other problem with our comparator function is that, though I can't trace its origin, I suspect that it was not built to be tested, but rather tweaked to make a test pass. We require that [a vector with duplicates be rejected as "not sorted."](https://github.com/bigladder/btwxt/blob/b4d0e17c3fff937715007201e2e9dc4ee8c06ad0/test/grid-axis-tests.cpp#L25) But, as far as strict weak ordering is concerned, something like {1, 3, 3, 5, 9} _is_ sorted. It looks for all the world as if we wrote the predicate to std::is_sorted _in order to return the result we wanted for full grid-axis validity_, rather than writing a valid predicate just for sort. The fact that a vector with dupes doesn't work as a grid-axis is a different check entirely, but we've convoluted the requirements by naming the checking function "`vector_is_sorted()`." The function should actually check for both sortedness and duplication, and be called something like `vector_is_valid_grid_axis()`.

I can think of two solutions after fixing the predicate. First, check that the vector is sorted and then check that no adjacent values are equal. Or, convert the vector to a std::set, and see if the sizes of the vector and set are the same.

**Comment by nealkruis** [comment]
PODs? I think your first option makes sense using `std::is_sorted` and `std::adjacent_find`.

**Comment by tanaya-mankad** [comment]
Plain old data. int, float, char...

**Comment by shorowit** [comment]
@tanaya-mankad Should this be closed? I see a related PR was merged.
